#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================


source /usr/share/yunohost/helpers

encryption_level=5
ynh_app_setting_set --key=encryption_level --value=$encryption_level
cipher=$(python3 -c "import os, base64; print(base64.b64encode(os.urandom(32)).decode())")
ynh_app_setting_set --key=cipher --value=$cipher

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

mv $install_dir/gokapi-* $install_dir/gokapi
chmod +x $install_dir/gokapi

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="config.json" --destination="$install_dir/config.json"

chown "$app:$app" "$install_dir/config.json"

ynh_exec_as_app env GOKAPI_DATA_DIR=$data_dir GOKAPI_CONFIG_DIR=$install_dir $install_dir/gokapi --config $install_dir/config.json --deployment-password $password

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd
yunohost service add "$app" --description="Lightweight server to share files" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start" --log_path="systemd" --wait_until="Webserver can be accessed at"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
